apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food
  template:
    metadata:
      labels:
        app: food
    spec:
      containers:
      - name: food-app
        image: food-delivery:latest
        ports:
        - containerPort: 8080
